# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        gdm
        gnome-backgrounds 
        gnome-console
        gnome-control-center
        gnome-disk-utility 
        gnome-keyring 
        gnome-session
        gnome-shell
        gnome-software
        gst-thumbnailers 
        gvfs-afc 
        gvfs-goa 
        gvfs-gphoto2
        gvfs-mtp
        nautilus
        power-profiles-daemon
        xdg-desktop-portal-gnome
