# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        btrfs-progs
        dosfstools
        efibootmgr
        fwupd
        git
        less
        libfido2
        linux
        make
        nano
        openssh
        polkit
        tpm2-tools
        tpm2-tss
        tree

# NetworkManager is used in the desktop profiles
RemoveFiles=    
        /usr/lib/systemd/network/89-ethernet.network  

VolatilePackages=
        systemd
        systemd-ukify
        udev

InitrdVolatilePackages=
        systemd
        udev

KernelInitrdModules=
        /drivers/gpu/drm
