# SPDX-License-Identifier: LGPL-2.1-or-later

[Distribution]
Distribution=arch

[Content]
Packages=
        bash-completion
        fakeroot
        flatpak
        irqbalance
        noto-fonts-emoji
        noto-fonts-cjk
        nss-mdns
        pacman-contrib
        sof-firmware
        wireless-regdb

RemoveFiles=
        /boot/*-ucode.img
