# SPDX-License-Identifier: LGPL-2.1-or-later

[Distribution]
Distribution=arch

[Content]
Packages=
        age
        bash-completion        
        flatpak
        irqbalance
        noto-fonts-emoji
        noto-fonts-cjk
        pacman-contrib
        sof-firmware
        tela-circle-icon-theme-dracula
        vimix-cursors
        wireless-regdb

RemoveFiles=
        /boot/*-ucode.img
