# SPDX-License-Identifier: LGPL-2.1-or-later

[Distribution]
Distribution=arch

[Content]
Packages=
        bash-completion
        cups
        cups-pdf
        fakeroot
        flatpak
        irqbalance
        noto-fonts-emoji
        noto-fonts-cjk
        pacman-contrib
        sof-firmware

RemoveFiles=
        /boot/*-ucode.img
