[Build]
WorkspaceDirectory=../../mkosi.work

[Runtime]
Drives=btrfs:30G
QemuArgs=-device nvme,serial=btrfs,drive=btrfs

[Distribution]
Distribution=arch

[Config]
#Profiles=gnome,intel

[Content]
RemoveFiles=
	/usr/lib/tmpfiles.d/shadow.conf
