[Content]
KernelInitrdModules=
        ahci
        amd_atl
        amd_ctl
        amd-pmc
        amd64_edac
        atkbd
        autofs4
        binfmt_misc
        btrfs
        cdrom
        cfg80211
        configfs
        crc-ccitt
        dm-crypt
        dm-integrity
        dm-mod
        dm-multipath
        dm-raid
        dm-verity
        dmi-sysfs
        drm_buddy
        drm_display_helper
        edac_mce_amd
        efi-pstore
        efivarfs
        erofs
        evdev
        ext4
        hid-generic
        i2c-algo-bit
        i2c_hid_acpi
        i2c-mux
        i2c-smbus
        i8042
        intel-gtt
        intel_pmc_ssram_telemetry
        intel_rapl_common
        intel-uncore-frequency-common
        intel-vsec
        kvm
        libphy
        loop
        mdio_devres
        mei
        mxm-wmi
        nvme
        nvmet-tcp
        overlay
        parport
        pmt_telemetry
        qemu_fw_cfg
        raid[0-9]*
        rapl
        scsi_mod
        sd_mod
        serio
        sg
        skx_edac_common
        squashfs
        thunderbolt_net
        tpm_tis
        tpm_vtpm_proxy
        ttm
        typec_ucsi
        ucsi_acpi
        usbhid
        usb-storage
        uvc
        vfat
        video
        videobuf2-v4l2
        videobuf2-vmalloc
        virtio_balloon
        virtio_blk
        virtio_console
        virtio_dma_buf
        virtio_mmio
        virtio_net
        virtio_pci
        virtio_scsi
        virtio-rng
        virtiofs
        vmd
        vmw_vsock_virtio_transport
        vsock
        watchdog
        wmi
        wmi-bmof
        x_tables
        xfs
        xhci-pci-renesas
        /fs/nls/
        crypto/
        -/drivers/crypto/ # exclude specialized hardware
        ccp_crypto # AMD crypto accelerator available in ryzen
        zram      # for early/systemd-zram-setup
        nfnetlink # for firewalld.service
        xe
