[Content]
KernelInitrdModules=
        ac
        acpi_cpufreq
        acpi_pad
        acpi_tad
        aesni_intel
        atkbd
        battery
        btrfs
        btusb
        button
        coretemp
        dummy
        ee1004
        efi_pstore
        evdev
        fjes
        ghash_clmulni_intel
        gpio_keys
        hid_multitouch
        i2c_designware_platform
        i2c_hid_acpi
        i2c_i801
        i8042
        i915
        iTCO_wdt
        idma64
        igen6_edac
        int3400_thermal
        int3403_thermal
        intel_cstate
        intel_hid
        intel_lpss
        intel_lpss_pci
        intel_oc_wdt
        intel_pmc_core
        intel_powerclamp
        intel_rapl_common
        intel_rapl_msr
        intel_tcc_cooling
        intel_uncore
        intel_uncore_frequency
        intel_vsec
        iwlwifi
        joydev
        kvm_intel
        mac_hid
        mei_hdcp
        mei_me
        mei_pxp
        mousedev
        msi_ec
        msi_wmi
        msi_wmi_platform
        nvme
        pcspkr
        pinctrl_tigerlake
        pmt_telemetry
        processor
        processor_thermal_device_pci_legacy
        psmouse
        rapl
        rtc_cmos
        rtsx_pci
        rtsx_pci_sdmmc
        serio_raw
        shpchp
        snd_hda_codec_alc269
        snd_hda_codec_intelhdmi
        snd_hda_intel
        snd_soc_avs
        snd_soc_dmic
        snd_soc_skl_hda_dsp
        snd_sof_pci_intel_tgl
        snd_sof_probes
        soc_button_array
        spi_intel_pci
        spi_nor
        thermal
        thunderbolt
        tpm_crb
        tpm_tis
        usbcore
        uvcvideo
        video
        wmi
        wmi_bmof
        x86_pkg_temp_thermal
        xe
        xhci_hcd
        xhci_pci
