# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        age
        clinfo
        libva-utils
        gocryptfs
        fakeroot
        syncthing
        tailscale
        tela-circle-icon-theme-dracula
        vimix-cursors
        mkinitcpio
