[Match]
Distribution=arch

[Content]
Packages=
    firefox-i18n-fr
    pacman-contrib
    tela-circle-icon-theme-dracula
    gnome-tweaks
    showtime
    flatpak
    thermald
    vpl-gpu-rt
    gst-plugin-va
    make
    linux-firmware-intel
    linux-firmware-other

#vulkan video ?

RemovePackages=
    amd-ucode
    fish
    gnome-tour
    linux-firmware
    vulkan-nouveau
    vulkan-radeon
