[Match]
Distribution=arch
    
[Content]
Packages=
	firefox-i18n-fr
	pacman-contrib
	papirus-icon-theme    
	gnome-tweaks
	showtime
	flatpak
	fakeroot
	thermald
	vpl-gpu-rt
	gst-plugin-va
	make

#vulkan video ?

RemovePackages=
    amd-ucode
    vulkan-nouveau
    vulkan-radeon
    gnome-tour
    fish
